apiVersion: v1
kind: Service
metadata:
  name: automotive-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: automotive-service
