# Example dbt profile for local Postgres DW
dw_demo:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      pass: postgres
      port: 5432
      dbname: dw_demo
      schema: public
