groups:
  - name: api-alerts
    rules:
      - alert: HighApiLatency
        expr: histogram_quantile(0.95, sum(rate(http_server_duration_seconds_bucket[5m])) by (le, service)) > 0.3
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "API p95 latency > 300ms"
      - alert: HighErrorRate
        expr: sum(rate(http_server_errors_total[5m])) by (service) > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "API error rate > 5/min"
      - alert: DBSlowQuery
        expr: sum(rate(pg_stat_activity_duration_seconds_bucket[5m])) by (le, service) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "DB slow queries > 1/min"
      - alert: QueueLag
        expr: sum(rate(rabbitmq_queue_messages_ready[5m])) by (queue) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Queue lag > 10 messages"
      - alert: CacheMissRate
        expr: (sum(rate(redis_keyspace_misses_total[5m])) / (sum(rate(redis_keyspace_hits_total[5m])) + sum(rate(redis_keyspace_misses_total[5m]))) > 0.2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Cache miss rate > 20%"
