global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
  - job_name: 'api-services'
    static_configs:
      - targets: ['apps-auth-service:3001', 'apps-garage-service:3002', 'apps-inventory-service:3003', 'apps-frontend-web:3000']
